# List

<h2>Soal 1: Sifat List</h2>

Jawab Pertanyaan di bawah ini:

Jenis data apa saja yang bisa ada di dalam List?

# JAWABAN :

### Tipe data yang dapat di masukkan ke dalam list yaitu tipe data, String, Float, Interger dan Boolean

<h2>Soal 2: Akses List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [2]:
a = ['1', '13b', 'aa1', 1.32, 22.1, 2.34]
# slicing list
print(a[1:5])

['13b', 'aa1', 1.32, 22.1]


Expected Output :

[ '13b', 'aa1', 1.32, 22.1 ]

<h2>Soal 3: Nested List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [16]:
a = [1.32, 22.1, 2.34]
b = ['1', '13b', 'aa1']
c = [3, 40, 100]
# combine list
'''Ada beberapa cara jalan'''
d = [a] + [c] + [b]
e = [a,c,b]
print(d)
print(e)
print([a] + [c] + [b])

[[1.32, 22.1, 2.34], [3, 40, 100], ['1', '13b', 'aa1']]
[[1.32, 22.1, 2.34], [3, 40, 100], ['1', '13b', 'aa1']]
[[1.32, 22.1, 2.34], [3, 40, 100], ['1', '13b', 'aa1']]


Expected Output :

[ [1.32, 22.1, 2.34], [3, 40, 100], ['1', '13b', 'aa1'] ]

<h2>Soal 4: Akses Nested List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [18]:
a = [
    [5, 9, 8],
    [0, 0, 6]
    ]
# subsetting list
print(a[1][1:])

[0, 6]


Expected Output :


[0, 6]

<h2>Soal 5: Built in Function List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [22]:
p = [0, 5, 2, 10, 4, 9]
# ordered list
print(sorted(p))

# get max value of list
print(max(p))

[0, 2, 4, 5, 9, 10]
10


Expected Output :

[0, 2, 4, 5, 9, 10]

10

<h2>Soal 6: List Operation</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [24]:
a = [1, 3, 5]
b = [5, 1, 3]
# combine list
'''ada beberapa cara'''
d = b + a
print(d)
print(b + a)

[5, 1, 3, 1, 3, 5]
[5, 1, 3, 1, 3, 5]


Expected Output :

[5, 1, 3, 1, 3, 5]

<h2>Soal 7: List Manipulation</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [27]:
a = [
    [5, 9, 8],
    [0, 0, 6]
    ]
# change list value
a[0][2] = 10
a[1][0] = 11

print(a)

[[5, 9, 10], [11, 0, 6]]


Expected Output :

[ [5, 9, 10], [11, 0, 6] ]

<h2>Soal 8: Delete Element List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [30]:
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

# Hilangkan elemen yang bernilai "bathroom" dan 10.50 dalam satu statement code
del(areas[8:10])

print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'poolhouse', 24.5, 'garage', 15.45]


Expected Output:

['hallway',
 11.25,
 'kitchen',
 18.0,
 'chill zone',
 20.0,
 'bedroom',
 10.75,
 'poolhouse',
 24.5,
 'garage',
 15.45]



## Soal 9: List Comprehension

Gunakan metode **list comprehension** untuk mencari anggota dari S yang habis di bagi 2, kemudian assign hasilnya dalam bentuk list ke dalam variabel T.

In [35]:
S = [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
T = []

for i in S:
  if i % 2 == 0:
    T.append(i)

print(T)

[0, 4, 16, 36, 64]


Expected Output:

[0, 4, 16, 36, 64]

# Dictionary

<h2>Soal 10: Akses Dictionary</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [37]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin', 'norway':'oslo' }

# print semua key yang ada di objek europe
print(europe.keys())


# print nilai dari key france
print(europe['france'])


dict_keys(['spain', 'france', 'germany', 'norway'])
paris


Expected Output:

dict_keys(['spain', 'france', 'germany', 'norway'])

paris

<h2>Soal 11: Menambahkan key-value baru ke Dictionary</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [43]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin', 'norway':'oslo' }

# tambahkan key itali ke objek dictionary dengan value roma
europe['italia'] = 'roma'
print(europe)
# cek apakah itali ada di dalam objek dictionary
print('italia' in europe)

{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo', 'italia': 'roma'}
True


Expected Output:
    
True

<h2>Soal 12: Update dan Remove Dictinary</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [48]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'bonn',
          'norway':'oslo', 'italy':'rome', 'poland':'warsaw',
          'australia':'vienna' }

# update nilai ibukota german ke berlin
europe['germany'] = 'berlin'
print(europe)
# remove australia dari europa
del europe['australia']
print(europe)

{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo', 'italy': 'rome', 'poland': 'warsaw', 'australia': 'vienna'}
{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo', 'italy': 'rome', 'poland': 'warsaw'}


Expected Output:

{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo', 'italy': 'rome', 'poland': 'warsaw'}

<h2>Soal 13: Nested Dictionary</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [50]:
country = { 
           'spain': { 'capital':'madrid', 'population':46.77 },
           'france': { 'capital':'paris', 'population':66.03 },
           'germany': { 'capital':'berlin', 'population':80.62 },
           'norway': { 'capital':'oslo', 'population':5.084 } 
         }

# berapa populasi dari kota german?
print(country['germany']['population'])
# update data baru, yaitu negara indonesia dengan capital jakarta dan poulasi 250
country['indonesia'] = {'capital':'jakarta', 'population':250}
print(country)

80.62
{'spain': {'capital': 'madrid', 'population': 46.77}, 'france': {'capital': 'paris', 'population': 66.03}, 'germany': {'capital': 'berlin', 'population': 80.62}, 'norway': {'capital': 'oslo', 'population': 5.084}, 'indonesia': {'capital': 'jakarta', 'population': 250}}


Expected Output:

80.62

{'spain': {'capital': 'madrid', 'population': 46.77}, 'france': {'capital': 'paris', 'population': 66.03}, 'germany': {'capital': 'berlin', 'population': 80.62}, 'norway': {'capital': 'oslo', 'population': 5.084}, 'indonesia': {'capital': 'jakarta', 'population': 250}}

<h2>Soal 14: Loop Dictionary</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [51]:
country = { 
           'spain': { 'capital':'madrid', 'population':46.77 },
           'france': { 'capital':'paris', 'population':66.03 },
           'germany': { 'capital':'berlin', 'population':80.62 },
           'norway': { 'capital':'oslo', 'population':5.084 },
           'indonesia' : {'capital':'jakarta', 'population':250}
         }

for negara in country:
  print('Ibukota', negara, ' adalah ', country[negara]['capital'])

Ibukota spain  adalah  madrid
Ibukota france  adalah  paris
Ibukota germany  adalah  berlin
Ibukota norway  adalah  oslo
Ibukota indonesia  adalah  jakarta


Expected Output:
    
Ibukota spain adalah madrid

Ibukota france adalah paris

Ibukota germany adalah berlin

Ibukota norway adalah oslo

Ibukota indonesia adalah jakarta

<h2>Soal 15: Loop List Tuple</h2>
    
diberikan list of tuples yang berisi provinsi, jumlah kasus kemarin, jumlah kasus hari ini, tampilkan persentase penambahan untuk masing-masing elemen. persentase penambahan dihitung sebagai (jumlah kasus hari ini - jumlah kasus kemarin)/jumlah kasus kemarin

In [53]:
zona_merah_tuples=[('Jawa Timur',5135,5318),('Banten',883,954),('Kalimantan Selatan',969,1033),('Sulawesi Selatan',1630,1668)]

In [56]:
for i in zona_merah_tuples:
  precentage = (i[2]-i[1]) / i[1]
  print('Kasus di provinsi {} : {}'.format(i[0], precentage))

Kasus di provinsi Jawa Timur : 0.03563777994157741
Kasus di provinsi Banten : 0.08040770101925254
Kasus di provinsi Kalimantan Selatan : 0.06604747162022703
Kasus di provinsi Sulawesi Selatan : 0.023312883435582823


<h2>Soal 16: Loop List Tuple</h2>

lengkapi baris kode dibawah dengan perulangan untuk menyimpan bilangan satuan (hint: bilangan yg kurang dari 10) saja dari list yang diberikan. dan menampilkannya ke layar sebagai list yang berbeda

In [57]:
list_angka=[50,3,7,888,25,9,101,28]
list_result=[]

for i in list_angka:
  if i < 10:
    list_result.append(i)

print(list_result)

[3, 7, 9]
